name: Lint
on:
  workflow_call:
    inputs:
      node-versions:
        description: 'JSON array of Node.js versions to test against'
        required: false
        type: string
        default: '[20, 22]'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON(inputs.node-versions) }}
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - run: yarn --prefer-offline --frozen-lockfile
      - run: yarn lint
